version: '3.7'
services:
  swag:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: linuxserver/swag:1.13.0-ls50
    cap_add:
      - NET_ADMIN
    container_name: swag
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - URL=${DOMAIN}
      - SUBDOMAINS=${SUBDOMAIN}
      - VALIDATION=http \
      - ONLY_SUBDOMAINS=${ONLYSUBDOMAINS}
    volumes:
      - ./config:/config
    restart: unless-stopped
    networks:
      - quiznow_network
    ports:
      - 80:80
      - 443:443

networks:
  quiznow_network:
    external: true